# Generated by Django 4.0.4 on 2022-05-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladyd_event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='name',
            field=models.CharField(default='Null-value', max_length=100),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='image',
            field=models.FileField(blank=True, default='default.png', upload_to=''),
        ),
    ]
