# Generated by Django 4.0.4 on 2022-05-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladyd_event', '0002_pictures_name_alter_pictures_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('service_image', models.FileField(blank=True, default='default.png', upload_to='')),
            ],
        ),
    ]
