# Generated by Django 4.0.4 on 2022-06-01 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladyd_event', '0004_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
